config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls"), name="tube"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる

    path('delete/<int:pk>', views.delete, name="delete"),
    path('update/<int:pk>', views.update, name="update"),
]

tube/models.py
from django.db import models
from django.utils import timezone

class Video(models.Model):

    class Meta:
        db_table = "video"

    title   = models.CharField(verbose_name="タイトル", max_length=30)
    comment = models.CharField(verbose_name="動画説明文", max_length=2000)
    dt      = models.DateTimeField(verbose_name="投稿日", default=timezone.now)
    edited  = models.BooleanField(default=False)

    image   = models.ImageField(verbose_name="画像",upload_to="tube/image/",blank=True)
    pdf     = models.FileField(verbose_name="PDF",upload_to="tube/pdf/",blank=True)

    def __str__(self):
        return self.title


tube/forms.py
from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model  = Video
        fields = ["title", "comment","image", "pdf" ]

class VideoEditForm(forms.ModelForm):
    class Meta:
        model  = Video
        fields = ["title", "comment", "dt",]

tube/views.py
from django.shortcuts import render, redirect

from django.views import View
from .models import Video
from .forms import VideoForm, VideoEditForm

from django.db.models import Q


#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

import magic
ALLOWED_MIME    = [ "application/pdf" ]

class IndexView(View):

    def get(self, request, *args, **kwargs):

        if "search" in request.GET:

            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("tube:index")


            search = request.GET["search"].replace("　", " ")
            search_list = search.split(" ")


            query = Q()
            for word in search_list:

                if "option" in request.GET:
                    query |= Q(comment__contains=word)
                else:
                    query &= Q(comment__contains=word)


            videos = Video.objects.filter(query).order_by("-dt")
        else:
            videos = Video.objects.all().order_by("-dt")


        context = {"videos": videos}


        return render(request, "tube/index.html", context)

    def post(self, request, *args, **kwargs):

        #TIPS:request.POSTだけでなく、request.FILESも引数に入れる。
        formset     = VideoForm(request.POST, request.FILES)



        fileflag    = False

        #TIPS:投稿されているPDFファイルが本当にPDFファイルかチェックする(MIMEで)
        if "pdf" in request.FILES:
            mime_type   = magic.from_buffer(request.FILES["pdf"].read(1024) , mime=True)
            if mime_type in ALLOWED_MIME:
                fileflag    = True
        else:
            fileflag    = True

        # ↑アップロードされたファイルが許可されているMIMEである、もしくはアップロードされていない場合。リクエストの保存を許可する。


        if formset.is_valid():
            print("バリデーションOK")

            if fileflag:
                formset.save()
            else:
                print("このファイルは許可されていません。")

        else:
            print("バリデーションエラー")


        return redirect("tube:index")

index = IndexView.as_view()


class DeleteView(View):

    def get(self, request, pk, *args, **kwargs):

        video   = Video.objects.filter(id=pk).first()
        context = { "video":video }

        return render(request, "tube/delete.html", context )


    def post(self, request, pk, *args, **kwargs):

        print("削除")

        # .first()で一番上のレコードを1つ取る。
        video    = Video.objects.filter(id=pk).first()
        video.delete()

        # TIPS:すでにurls.pyにてpkが数値型であることがわかっているので、バリデーションをする必要はない。

        return redirect("tube:index")

delete = DeleteView.as_view()


class UpdateView(View):

    def get(self, request, pk, *args, **kwargs):

        video   = Video.objects.filter(id=pk).first()
        context = { "video":video }

        return render(request, "tube/update.html", context )

    def post(self, request, pk, *args, **kwargs):

        # まず、編集対象のレコード特定
        instance    = Video.objects.filter(id=pk).first()

        # 第2引数にinstanceを指定することで、対象の編集ができる。
        formset     = VideoEditForm(request.POST, instance=instance)

        if formset.is_valid():
            print("バリデーションOK")
            formset.save()

            Video.objects.filter(id=pk).update(edited=True)

        else:
            print("バリデーションNG")

        return redirect("tube:index")


update  = UpdateView.as_view()

templates/common/sidebar.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block site_title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>


    <!--静的ファイルの読み込みは html冒頭でload staticのテンプレートタグを記述した後、下記のように読み込み指定する。-->
    <link rel="stylesheet" href="{% static 'common/css/style.css' %}">

    {% block extra_head %}
    {% endblock %}

</head>
<body>

    <header>
        <h1>{% block page_title %}{% endblock %}</h1>
    </header>


    <main>
    {% block main %}
    {% endblock %}
    </main>



</body>
</html>



templates/tube/delete.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
         <title>削除ページ</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <style>
        h2 {
           color: red;
           font-weight: bold;
           }
    </style>
</head>

<body>
    <h2>Worning!</h2>
    <div>
        <p>一度削除すると、元に戻すことが出来ません。本当に削除しますか？</p>
    </div>

          <form action="{% url 'tube:delete' video.id %}" method ="POST" style="display:inline-block;">
            {% csrf_token %}
            <button class="btn btn-danger">Yes</button>
          </form>

           <a class="btn btn-success" href="{% url 'tube:index' %}">No</a>


</body>
</html>

templates/tube/index.html
{% extends "common/sidebar.html" %}


{% block site_title %}サイトのタイトル{% endblock %}


{% block extra_head %}
<script>console.log("追加のcssやjsがあればここにまとめて書く");</script>
<style>
    .sort {
       float: right;
       margin-right: 30%;
       font-weight: bold;
       color: chartreuse;
    }
</style>
{% endblock %}



{% block page_title %}{% endblock %}

{% block main %}
<main class="container">

    <form method="GET">
        <div>OR検索はチェックを入れる:<input type="checkbox" name="option" {% if request.GET.option %}checked{% endif %}></div>
        <input type="text" name="search" value="{{ request.GET.search }}">
        <input type="submit" value="検索">
    </form>


    <!--TIPS:ファイルをアップロードする場合、 enctype="multipart/form-data" をformタグに入れる。-->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div><input class="form-text" placeholder="タイトル..." name="title" value="{{ request.POST.title }}"></div>
        <div><textarea class="form-control" name="comment" placeholder="概要欄...">{{ video.comment }}</textarea></div>
        <div>画像:<input type="file" name="image"></div>
        <div>PDF:<input type="file" name="pdf"></div>
        <input class="form-control my-2" type="submit" value="送信">

    </form>

      {% for video in videos %}
    <div class="border">
        <div>{{ video.id }}</div>

          {% if video.edited %}
             <p class="sort">Edited</p>
          {% endif %}

        <div>タイトル：{{ video.title }}</div>

        <div>概要欄 ：{{ video.comment }}</div>

        <div> {% if video.edited %}更新日 ：{{ video.dt }}
              {% else %}投稿日 ：{{ video.dt }}
              {% endif %}
        </div>

        {% if video.image %}<div><img src="/media/{{ video.image }}" alt="投稿された画像"></div>{% endif %}
        {% if video.pdf %}<div><a href="/media/{{ video.pdf }}">{{ video.pdf }}</a></div>{% endif %}

        <a class="btn btn-danger" href="{% url 'tube:delete' video.id %}">削除</a>

        <a class="btn btn-success" href="{% url 'tube:update' video.id %}">編集</a>

    </div>
      {% endfor %}




</main>
{% endblock %}





{# ユーザーがログイン済みの場合、userのis_authenticated属性値で判定できる。 #}
  {#% if user.is_authenticated %#}
 {# <div>こんにちは{{ user.get_username }}さん</div> #}
  {#% else %#}
  {# <div>ログインしてください</div> #}
  {#% endif %#}



templates/tube/update.html
<!DOCTYPE html>
<html lang="ja">
<head>
         <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
         <title>編集</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


</head>
<body>

    <form method="POST">
        {% csrf_token %}

        <div><input class="form-text" placeholder="タイトル..." name="title" value="{{ video.title }}"></div>
        <!--TIPS:textarea属性にvalue属性は存在しない、中のタグに値を入れる。-->
        <div><textarea class="form-control" name="comment" placeholder="概要欄...">{{ video.comment }}</textarea></div>
        <div><input class="form-text" placeholder="更新日..." name="dt" value="{{ video.dt|date:'Y-m-d H:i' }}"></div>

        <input type="submit" value="送信">

    </form>

</body>
</html>